### PR TITLE
Issue #34 - Print the additional platforms in the `description` table column

### PR DESCRIPTION
**Pull request by martin-g**
Prints the optional additional platforms in the `description` column of the Index table.
Also prints the platforms in the recipe's details page.

recipe-details
index-page

~This is still work in progress! I'll try to make the Index table more dynamic by using https://datatables.net/~

### CODE REVIEW

**Comment by martin-g** [comment]
Here is the new version of the Package Index page based on DataTables.net:
package-index-datatables net

I tried to keep it similar to the current UI of that page but if you have ideas how to improve its user experience I'll be glad to implement them!

You could try it at https://dc52-212-50-92-101.ngrok-free.app/conda-package_index.html
Note: it runs on my dev machine, so it might be broken sometimes or offline.

**Comment by martin-g** [comment]
package-index-datatables

**Comment by bgruening** [comment]
Cool, I like it :)

**Comment by martin-g** [comment]
> Why does it show just 63 recipes ?

Because building all recipes takes a lot of time :-)
I use `BIOCONDA_FILTER_RECIPES=63 make html` to build just 63 of them. A random number.

I just built them all:
package-index-datatables

**Comment by martin-g** [comment]
package-index-datatables

**Comment by martin-g** [comment]
Added info about `noarch` recipes:

package-index-datatables


Any ideas how to detect whether a recipe is enabled for `linux-64` and `osx-64` ? Those are implicit, i.e. not explicitly listed in meta.yaml, and they could be disabled via `build > skip: True # [...]`

**Comment by martin-g** [comment]
I think I figured how to list all available platform builds for a recipe by using the RepoData:

package-index-datatables

**Comment by martin-g** [comment]
I don't have more ideas for improvements for this PR!

**Review by bgruening — APPROVED** [review]
... and I don't have anything to complain :) Great stuff @martin-g!

**Comment by daler** [comment]
@martin-g this is great, thank you!

**Comment by martin-g** [comment]
I'm glad you all like it! :-)

**Pull request merged**
